
import type { Metadata } from "next";
import "./globals.css";
import Theme from "@/providers/ThemeProvider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";



export const metadata: Metadata = {
  title: "codingo plus",
  description: "Generated by mobin heydari",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl" suppressHydrationWarning>
      <body className="dark:bg-base-dark bg-base-light font-custom flex flex-col justify-between gap-9">
        <Theme>
          <Navbar />
          {children}
          <Footer />
        </Theme>
      </body>
    </html>
  );
}