# Generated by Django 5.2.4 on 2025-07-21 09:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliparts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clipart',
            name='text',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='متن نماهنگ'),
            preserve_default=False,
        ),
    ]
