# Generated by Django 5.2.4 on 2025-10-01 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliparts', '0002_clipart_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clipart',
            name='music',
        ),
    ]
