# Generated by Django 5.2.4 on 2025-09-13 08:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('title', models.CharField(max_length=250, verbose_name='عنوان')),
                ('slug', models.CharField(max_length=250, primary_key=True, serialize=False, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('poster', models.ImageField(upload_to='Show/posters/', verbose_name='پوستر')),
                ('video', models.URLField(verbose_name='آدرس ویدیو')),
                ('text', ckeditor.fields.RichTextField(verbose_name='متن نماهنگ')),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بهروزرسانی')),
            ],
            options={
                'verbose_name': 'نمایش',
                'verbose_name_plural': 'نمایش ها',
            },
        ),
    ]
