# Generated by Django 5.2.4 on 2025-09-13 08:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='description',
            field=models.TextField(verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='show',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='تکست'),
        ),
    ]
