# Generated by Django 5.2.4 on 2025-09-04 08:56

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funny',
            fields=[
                ('title', models.CharField(max_length=250, verbose_name='عنوان')),
                ('slug', models.CharField(max_length=250, primary_key=True, serialize=False, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('poster', models.ImageField(upload_to='funny/posters/', verbose_name='پوستر')),
                ('video', models.URLField(verbose_name='آدرس ویدیو')),
                ('text', ckeditor.fields.RichTextField(verbose_name='متن نماهنگ')),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بهروزرسانی')),
            ],
            options={
                'verbose_name': 'نماهنگ',
                'verbose_name_plural': 'نماهنگ ها',
            },
        ),
        migrations.CreateModel(
            name='FunnyContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان')),
                ('image', models.ImageField(blank=True, null=True, upload_to='funny/content/image/', verbose_name='تصویر')),
                ('video', models.URLField(blank=True, null=True, verbose_name='آدرس ویدیو')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='متن نماهنگ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بهروزرسانی')),
                ('funny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='Funny.funny', verbose_name='بامزه')),
            ],
        ),
    ]
