# Generated by Django 5.2.4 on 2025-09-13 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Funny', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funny',
            options={'verbose_name': 'بامزه', 'verbose_name_plural': 'بامزه ها'},
        ),
        migrations.AlterModelOptions(
            name='funnycontent',
            options={'verbose_name': 'محتوا', 'verbose_name_plural': 'محتوا ها'},
        ),
    ]
