# Generated by Django 5.2.4 on 2025-09-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funny', '0002_alter_funny_options_alter_funnycontent_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funnycontent',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='متن نماهنگ'),
        ),
    ]
