# Generated by Django 5.2.4 on 2025-07-26 11:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('title', models.CharField(max_length=250, verbose_name='عنوان')),
                ('slug', models.CharField(max_length=250, primary_key=True, serialize=False, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('poster', models.ImageField(upload_to='audios/posters/', verbose_name='پوستر')),
                ('music', models.FileField(upload_to='audios/musics/', verbose_name='صوت')),
                ('text', ckeditor.fields.RichTextField(verbose_name='متن صوت')),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بهروزرسانی')),
            ],
            options={
                'verbose_name': 'صوت',
                'verbose_name_plural': 'صوت ها',
            },
        ),
    ]
