# Generated by Django 5.2.4 on 2025-07-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('f_name', models.CharField(max_length=255, verbose_name='نام')),
                ('l_name', models.CharField(max_length=255, verbose_name='نام خانوادگی')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='تلفن')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('linkedin_id', models.CharField(blank=True, max_length=255, verbose_name='شناسه لینکدین')),
                ('status', models.CharField(choices=[('N', 'جدید'), ('I', 'در حال بررسی'), ('C', 'بررسی شده'), ('A', 'بایگانی شده')], default='N', help_text='وضعیت فعلی درخواست تماس.', max_length=3, verbose_name='وضعیت')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='آدرس IP بازدیدکننده برای امنیت یا تحلیل.', null=True, verbose_name='آدرس IP')),
                ('user_agent', models.CharField(blank=True, help_text='عامل کاربر مرورگر برای اطلاعات دستگاه.', max_length=512, null=True, verbose_name='عامل کاربر')),
                ('attachment', models.FileField(blank=True, help_text='ضمیمه فایل اختیاری مانند رزومه یا نمونه\u200cکار.', null=True, upload_to='contact_attachments/', verbose_name='فایل پیوست')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان به\u200cروزرسانی')),
                ('is_ignored', models.BooleanField(default=True, verbose_name='نادیده گرفته شده')),
                ('is_readed', models.BooleanField(default=False, verbose_name='خوانده شده')),
            ],
            options={
                'verbose_name': 'تماس',
                'verbose_name_plural': 'تماس\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
