# Generated by Django 5.2.4 on 2025-08-12 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0002_remove_contact_linkedin_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
    ]
