# Generated by Django 5.2.4 on 2025-07-26 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('title', models.CharField(max_length=250, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=250, primary_key=True, serialize=False, unique=True, verbose_name='اسلاگ')),
                ('poster', models.ImageField(upload_to='stories/posters', verbose_name='پوستر')),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بهروزرسانی')),
            ],
        ),
        migrations.CreateModel(
            name='StoryVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='stories/posters', verbose_name='ویدیو')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بهروزرسانی')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='Stories.story', verbose_name='استوری')),
            ],
        ),
    ]
