# Generated by Django 5.2.4 on 2025-07-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name': 'استوری', 'verbose_name_plural': 'استوری ها'},
        ),
        migrations.AlterModelOptions(
            name='storyvideos',
            options={'verbose_name': 'ویدیو', 'verbose_name_plural': 'ویدیو های استوری'},
        ),
        migrations.RemoveField(
            model_name='storyvideos',
            name='id',
        ),
        migrations.AddField(
            model_name='storyvideos',
            name='slug',
            field=models.SlugField(default=1, max_length=250, primary_key=True, serialize=False, unique=True, verbose_name='اسلاگ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storyvideos',
            name='title',
            field=models.CharField(default=1, max_length=250, verbose_name='عنوان'),
            preserve_default=False,
        ),
    ]
