# Generated by Django 5.2.4 on 2025-07-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stories', '0002_alter_story_options_alter_storyvideos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyvideos',
            name='video',
            field=models.URLField(verbose_name='آدرس ویدیو'),
        ),
    ]
